---
backend:
  name: git-gateway
  branch: master

site_url: https://montana-history-center.netlify.com

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    files:
      - name: index
        label: Home Page
        file: src/pages/index.md
        fields:
          - {default: index-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Eyebrow, name: eyebrow, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: text}
          - {label: Description, name: description, widget: text}
          - label: Call to Action
            name: cta
            widget: object
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Link, name: url, widget: string}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - {label: Quote, name: quote, widget: string}
              - {label: Author, name: author, widget: string}
          - label: Mainpitch
            name: mainpitch
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - label: Why
                name: why
                widget: object
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Points, name: points, widget: list}
              - label: Why Not
                name: whynot
                widget: object
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Points, name: points, widget: list}
          - label: Supporters
            name: supporters
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Clients
                name: clients
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Text, name: text, widget: text}
                  - label: Link
                    name: link
                    widget: object
                    fields:
                      - {label: Text, name: text, widget: string}
                      - {label: Link, name: url, widget: string}
          - label: Featured Links
            name: featuredLinks
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Links
                name: links
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
                  - label: Link
                    name: link
                    widget: object
                    fields:
                      - {label: Text, name: text, widget: string}
                      - {label: Link, name: url, widget: string}
      - name: mallsite
        label: Mall Site Page
        file: src/pages/why-the-mall-site/index.md
        fields:
          - {default: mallsite-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - label: Call to Action
            name: cta
            widget: object
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Link, name: url, widget: string}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - {label: Quote, name: quote, widget: string}
              - {label: Author, name: author, widget: string}
          - label: Mainpitch
            name: mainpitch
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Timeline
                label_singular: Event
                name: timeline
                widget: list
                fields:
                  - {label: 'Date(s)', name: date, widget: string}
                  - {label: Content, name: description, widget: text}
          - label: Midway Callout
            name: midway
            widget: text
          - label: Closer Callout
            name: closer
            widget: text
      - name: faq
        label: FAQ Page
        file: src/pages/faq/index.md
        fields:
          - {default: faq-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: text}
          - label: Questions
            name: questions
            label_singular: Question
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: text}
      - name: stories
        label: Stories of Support Page
        file: src/pages/stories-of-support/index.md
        fields:
          - {default: stories-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: text}
          - label: Call to Action
            name: cta
            widget: object
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Link, name: url, widget: string}
          - label: Callout Banner
            name: callout
            widget: object
            fields:
              - {label: Text, name: text, widget: string}
              - label: CTA
                name: cta
                widget: object
                fields:
                  - {label: Text, name: text, widget: string}
                  - {label: Link, name: url, widget: string}
          - label: Groups
            name: groups
            label_singular: Group
            widget: list
            fields:
              - {label: Group Name, name: name, widget: string}
              - label: Testimonials
                name: testimonials
                label_singular: Testimonial
                widget: list
                fields:
                  - {label: Quote, name: quote, widget: text}
                  - {label: Author, name: author, widget: text}
      - name: news
        label: News and Opinions Page
        file: src/pages/news-and-opinions/index.md
        fields:
          - {default: news-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: text}
          - label: Call to Action
            name: cta
            widget: object
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Link, name: url, widget: string}
          - label: Main Content
            name: main
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Press
                name: press
                label_singular: Press Item
                widget: list
                identifier_field: title
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Press Name, name: name, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: URL, name: url, widget: string}
                  - {label: Date, name: date, format: "MMMM D, YYYY", widget: date}
                  - {label: Author, name: author, widget: string}
                  - {label: Quote, name: quote, widget: text}
      - name: about
        label: About
        file: src/pages/about/index.md
        fields:
          - {default: about-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: markdown}
      - name: contact
        label: Contact
        file: src/pages/contact/index.md
        fields:
          - {default: contact-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: markdown}
      - name: terms
        label: Terms
        file: src/pages/terms/index.md
        fields:
          - {default: terms-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: markdown}
      - name: privacy
        label: Privacy
        file: src/pages/privacy/index.md
        fields:
          - {default: privacy-page, label: Template Key, name: templateKey, widget: hidden}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: markdown}
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/pages/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    format: yaml-frontmatter
    create: true
    fields:
      - {default: blog-post, label: Template Key, name: templateKey, widget: hidden}
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: text}
      - {label: Featured Post, name: featuredpost, widget: boolean}
      - {label: Featured Image, name: featuredimage, widget: image}
      - {label: Body, name: body, widget: markdown}
      - {label: Tags, name: tags, widget: list}
    meta:
      - {label: 'SEO Description', name: 'description', widget: 'text'}

