backend:
	name: git-gateway
	branch: master

media_folder: static/img
public_folder: /img

collections:
	- name: 'blog'
		label: 'Blog'
		folder: 'src/pages/blog'
		create: true
		slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
		fields:
			- {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post'}
			- {label: 'Title', name: 'title', widget: 'string'}
			- {label: 'Publish Date', name: 'date', widget: 'datetime'}
			- {label: 'Description', name: 'description', widget: 'text'}
			- {label: 'Featured Post', name: 'featuredpost', widget: 'boolean'}
			- {label: 'Featured Image', name: 'featuredimage', widget: image}
			- {label: 'Body', name: 'body', widget: 'markdown'}
			- {label: 'Tags', name: 'tags', widget: 'list'}

	- name: 'pages'
		label: 'Pages'
		files:
			- file: 'src/pages/index.md'
				label: 'Home Page'
				name: 'index'
				fields:
					- {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
					- {label: Title, name: title, widget: string}
					- {label: Image, name: image, widget: image}
					- {label: Eyebrow, name: eyebrow, widget: string}
					- {label: Heading, name: heading, widget: string}
					- {label: Subheading, name: subheading, widget: string}
					- {label: 'Call to Action', name: cta, widget: object, fields: [
							{label: Text, name: text, widget: string}
							{label: Link, name: url, widget: string}
						]}
					- {label: Testimonials, name: testimonials, widget: list, fields: [
							{label: Quote, name: quote, widget: string},
							{label: Author, name: author, widget: string}
						]}
					- {label: Mainpitch, name: mainpitch, widget: object, fields: [
							{label: Title, name: title, widget: string},
							{label: Image, name: image, widget: image},
							{label: Why, name: why, widget: object, fields: [
								{label: Heading, name: heading, widget: string},
								{label: Points, name: points, widget: list}
							]},
							{label: 'Why Not', name: whynot, widget: object, fields: [
								{label: Heading, name: heading, widget: string},
								{label: Points, name: points, widget: list}
							]},
						]}
					- {label: Description, name: description, widget: text}
					- {label: Supporters, name: supporters, widget: object, fields: [
							{label: Heading, name: heading, widget: string},
							{label: Description, name: description, widget: text},
							{label: Clients, name: clients, widget: list, fields: [
								{label: Image, name: image, widget: image},
								{label: Text, name: text, widget: text},
								{label: Link, name: link, widget: object, fields: [
									{label: Text, name: text, widget: string}
									{label: Link, name: url, widget: string}
								]}
							]}
						]}
					- {label: 'Featured Links', name: featuredLinks, widget: object, fields: [
							{label: Heading, name: heading, widget: string},
							{label: Description, name: description, widget: text},
							{label: Links, name: links, widget: list, fields: [
								{label: Image, name: image, widget: image},
								{label: Link, name: link, widget: object, fields: [
									{label: Text, name: text, widget: string}
									{label: Link, name: url, widget: string}
								]}
							]}
						]}

			- file: 'src/pages/about/index.md'
				label: 'About'
				name: 'about'
				fields:
					- {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page'}
					- {label: 'Title', name: 'title', widget: 'string'}
					- {label: 'Body', name: 'body', widget: 'markdown'}

			- file: 'src/pages/petition/index.md'
				label: 'Petition Page'
				name: 'petition'
				fields:
					- {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'petition-page'}
					- {label: Title, name: title, widget: string}
					- {label: Image, name: image, widget: image}
					- {label: Heading, name: heading, widget: string}
					- {label: Description, name: description, widget: string}
					- {label: Intro, name: intro, widget: object, fields: [
							{label: Heading, name: heading, widget: string},
							{label: Description, name: description, widget: text},
							{label: Blurbs, name: blurbs, widget: list, fields: [
								{label: Image, name: image, widget: image},
								{label: Text, name: text, widget: text}
							]}
						]}
					- {label: Main, name: main, widget: object, fields: [
							{label: Heading, name: heading, widget: string},
							{label: Description, name: description, widget: text},
							{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]},
							{label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]},
							{label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
						]}
					- {label: Testimonials, name: testimonials, widget: list, fields: [
							{label: Quote, name: quote, widget: string},
							{label: Author, name: author, widget: string}
						]}
